services:
  mongo:
    image: mongo
    ports:
      - "3456:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: example
    volumes:
      - mongo-data-dev:/data/db

  backend:
    image: backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://root:password@mongo:27017/example?authSource=admin
      - DB_NAME=db_name_dev
      - COLLECTION_NAME=collection_name_dev
    container_name: backend-dev
    depends_on:
      - mongo

  frontend:
    image: frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    container_name: frontend-dev
    depends_on:
      - backend

volumes:
  mongo-data-dev:
