services:
  backend:
    image: backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    container_name: backend-dev    

  frontend:
    image: frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    container_name: frontend-dev
    depends_on:
      - backend